version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.3.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: cdk/
      - run: 
          name: Typescript compile
          command: npm run build
          working_directory: cdk/
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: node/default
    parameters:
      region:
        default: us-east-2
        type: string
    environment:
      AWS_ACCOUNT: 923739627351
      AWS_DEFAULT_REGION: <<parameters.region>>
      CDK_NEW_BOOTSTRAP: 1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run: 
          name: CDK deploy
          command: npm run deploy
          working_directory: cdk

workflows:
  main:
    jobs:
      - build
      - deploy:
          region: us-east-1
          requires:
            - build