create table analytics.dwh_fincidents (
    "Incident Number" BIGINT PRIMARY KEY,
    "Incident Date" TIMESTAMP,
    "Call Number" CHAR(10),
    "Alarm DtTm" TIMESTAMP,
    "Arrival DtTm" TIMESTAMP,
    "Close DtTm" TIMESTAMP,
    "Suppression Units" INT,
    "Suppression Personnel" INT,
    "EMS Units" INT,
    "EMS Personnel" INT,
    "Other Units" INT,
    "Other Personnel" INT,
    "First Unit On Scene" VARCHAR(200),
    "Fire Fatalities" INT,
    "Fire Injuries" INT,
    "Civilian Fatalities" INT,
    "Civilian Injuries" INT,
    "Number of Alarms" INT,
    "Mutual Aid" VARCHAR(50),
    "Action Taken Primary" VARCHAR(200),
    "Action Taken Secondary" VARCHAR(200),
    "Action Taken Other" VARCHAR(200)
);

create table analytics.dwh_dgeography (
    "Incident Number" BIGINT PRIMARY KEY,
    "Address" VARCHAR(200),
    "City" VARCHAR(200),
    "zipcode" CHAR(20),
    "Battalion" VARCHAR(20),
    "Station Area" VARCHAR(20),
    "Box" VARCHAR(20),
    "Supervisor District" VARCHAR(50),
    "neighborhood_district" VARCHAR(50),
    "point" POINT
);

create table analytics.dwh_dbuildings (
    "Incident Number" BIGINT,
    "Exposure Number" INT,
    "Estimated Property Loss" NUMERIC,
    "Estimated Contents Loss" NUMERIC,
    "Detector Alerted Occupants" VARCHAR(200),
    "Property Use" VARCHAR(200),
    "Area of Fire Origin" VARCHAR(200),
    "Ignition Cause" VARCHAR(200),
    "Ignition Factor Primary" VARCHAR(200),
    "Ignition Factor Secondary" VARCHAR(200),
    "Heat Source" VARCHAR(200),
    "Item First Ignited" VARCHAR(200),
    "Human Factors Associated with Ignition" VARCHAR(200),
    "Structure Type" VARCHAR(200),
    "Structure Status" VARCHAR(200),
    "Floor of Fire Origin" INT,
    "Fire Spread" VARCHAR(200),
    "No Flame Spead" VARCHAR(20),
    "Number of floors with minimum damage" INT,
    "Number of floors with significant damage" INT,
    "Number of floors with heavy damage" INT,
    "Number of floors with extreme damage" INT,
    "Detectors Present" VARCHAR(200),
    "Detector Type" VARCHAR(200),
    "Detector Operation" VARCHAR(200),
    "Detector Effectiveness" VARCHAR(200),
    "Detector Failure Reason" VARCHAR(200),
    "Automatic Extinguishing System Present" VARCHAR(200),
    "Automatic Extinguishing Sytem Type" VARCHAR(200),
    "Automatic Extinguishing Sytem Perfomance" VARCHAR(200),
    "Automatic Extinguishing Sytem Failure Reason" VARCHAR(200),
    "Number of Sprinkler Heads Operating" INT,
    PRIMARY KEY ("Incident Number", "Exposure Number")
);


-- create table staging.dwh_fincidents (
--     "Incident Number" VARCHAR(200) PRIMARY KEY,
--     "Incident Date" VARCHAR(200),
--     "Call Number" VARCHAR(200),
--     "Alarm DtTm" VARCHAR(200),
--     "Arrival DtTm" VARCHAR(200),
--     "Close DtTm" VARCHAR(200),
--     "Suppression Units" VARCHAR(200),
--     "Suppression Personnel" VARCHAR(200),
--     "EMS Units" VARCHAR(200),
--     "EMS Personnel" VARCHAR(200),
--     "Other Units" VARCHAR(200),
--     "Other Personnel" VARCHAR(200),
--     "First Unit On Scene" VARCHAR(200),
--     "Fire Fatalities" VARCHAR(200),
--     "Fire Injuries" VARCHAR(200),
--     "Civilian Fatalities" VARCHAR(200),
--     "Civilian Injuries" VARCHAR(200),
--     "Number of Alarms" VARCHAR(200),
--     "Mutual Aid" VARCHAR(200),
--     "Action Taken Primary" VARCHAR(200),
--     "Action Taken Secondary" VARCHAR(200),
--     "Action Taken Other" VARCHAR(200)
-- );
